/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentinformationsystem;

/**
 *
 * @author LENOVO
 */
public class StudentGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentGUI.class.getName());

    /**
     * Creates new form StudentGUI
     */
   public StudentGUI() {
    initComponents();
    this.setLocationRelativeTo(null);
    loadStudentData(); // <-- ADD THIS LINE HERE
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Firts Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Age:");

        jLabel4.setText("Email:");

        txtAge.addActionListener(this::txtAgeActionPerformed);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Age", "Email"
            }
        ));
        studentTable.setToolTipText("");
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtEmail))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
// 1. Check if the user actually clicked on a row in the table first
int selectedRow = studentTable.getSelectedRow();

if (selectedRow == -1) {
    // If they didn't select anyone, show a warning and stop
    javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table to delete!");
    return;
}

// 2. Ask for confirmation (Good practice so they don't delete someone by accident!)
int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete this student?", 
        "Confirm Delete", 
        javax.swing.JOptionPane.YES_NO_OPTION);

if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    try {
        // 3. Grab the 'student_id' from the very first column (column 0) of the selected row
        int studentId = Integer.parseInt(studentTable.getValueAt(selectedRow, 0).toString());
        
        // 4. Connect to the database and write the DELETE SQL command
        java.sql.Connection conn = DBConnection.getConnection();
        String sql = "DELETE FROM students WHERE student_id = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        
        // 5. Attach the ID to the command and execute it
        pstmt.setInt(1, studentId);
        pstmt.executeUpdate();
        
        // 6. Tell the user it worked!
        javax.swing.JOptionPane.showMessageDialog(this, "Student Deleted Successfully!");
        
        // 7. Refresh the table instantly so the student disappears from the screen
        loadStudentData();
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // 1. Get the text that the user typed into the boxes
String firstName = txtFirstName.getText();
String lastName = txtLastName.getText();
String ageText = txtAge.getText();
String email = txtEmail.getText();

// 2. Check if any boxes are empty
if (firstName.isEmpty() || lastName.isEmpty() || ageText.isEmpty() || email.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
    return; // Stop the code here if a box is empty
}

try {
    // 3. Convert the age text into an actual Number (Integer)
    int age = Integer.parseInt(ageText);
    
    // 4. Connect to the database and prepare the SQL command
    java.sql.Connection conn = DBConnection.getConnection();
    String sql = "INSERT INTO students (first_name, last_name, age, email) VALUES (?, ?, ?, ?)";
    java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
    
    // 5. Fill in the '?' placeholders with our data
    pstmt.setString(1, firstName);
    pstmt.setString(2, lastName);
    pstmt.setInt(3, age);
    pstmt.setString(4, email);
    
    // 6. Execute the command to save it!
    pstmt.executeUpdate();
    
    // 7. Show a success popup
    javax.swing.JOptionPane.showMessageDialog(this, "Student Added Successfully!");
    
    // 8. Clear the boxes for the next entry
    txtFirstName.setText("");
    txtLastName.setText("");
    txtAge.setText("");
    txtEmail.setText("");
    txtFirstName.requestFocus();
    loadStudentData();

} catch (NumberFormatException e) {
    // If they typed a word instead of a number for Age
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Age must be a number!");
} catch (java.sql.SQLException e) {
    // If something goes wrong with the database
    javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnAddActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
// 1. Get the row that the user just clicked
int selectedRow = studentTable.getSelectedRow();

// 2. Get the table model
javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) studentTable.getModel();

// 3. Grab the data from the clicked row and put it into the text boxes
// (Column 1 is First Name, Column 2 is Last Name, etc. Column 0 is the ID, which we keep hidden)
txtFirstName.setText(model.getValueAt(selectedRow, 1).toString());
txtLastName.setText(model.getValueAt(selectedRow, 2).toString());
txtAge.setText(model.getValueAt(selectedRow, 3).toString());
txtEmail.setText(model.getValueAt(selectedRow, 4).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_studentTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
// 1. Check if a row is actually selected
int selectedRow = studentTable.getSelectedRow();
if (selectedRow == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table to update!");
    return;
}

try {
    // 2. Get the hidden ID of the student we are updating (from column 0)
    int studentId = Integer.parseInt(studentTable.getValueAt(selectedRow, 0).toString());
    
    // 3. Get the NEW text that the user typed into the boxes
    String firstName = txtFirstName.getText();
    String lastName = txtLastName.getText();
    int age = Integer.parseInt(txtAge.getText());
    String email = txtEmail.getText();
    
    // 4. Connect to database and write the UPDATE SQL command
    java.sql.Connection conn = DBConnection.getConnection();
    String sql = "UPDATE students SET first_name=?, last_name=?, age=?, email=? WHERE student_id=?";
    java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
    
    // 5. Attach the new data to the command
    pstmt.setString(1, firstName);
    pstmt.setString(2, lastName);
    pstmt.setInt(3, age);
    pstmt.setString(4, email);
    pstmt.setInt(5, studentId); // This tells MySQL exactly WHICH student to update
    
    // 6. Execute the update!
    pstmt.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Student Updated Successfully!");
    
    // 7. Refresh the table and clear the boxes
    loadStudentData();
    txtFirstName.setText("");
    txtLastName.setText("");
    txtAge.setText("");
    txtEmail.setText("");
    
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Age must be a number!");
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
// 1. Set all the text boxes to empty strings
txtFirstName.setText("");
txtLastName.setText("");
txtAge.setText("");
txtEmail.setText("");

// 2. Bonus trick: This puts the blinking typing cursor back into the First Name box!
txtFirstName.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentGUI().setVisible(true));
    }
    // --- METHOD TO LOAD DATA INTO THE TABLE ---
    private void loadStudentData() {
        try {
            // 1. Get the connection
            java.sql.Connection conn = DBConnection.getConnection();
            
            // 2. Prepare the SQL to select everything from the students table
            String sql = "SELECT * FROM students";
            java.sql.Statement stmt = conn.createStatement();
            
            // 3. Run the query and get the results
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            
            // 4. Get the visual table's "Model" (this controls the rows and columns)
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) studentTable.getModel();
            
            // 5. Wipe the table clean before loading new data so it doesn't duplicate
            model.setRowCount(0);
            
            // 6. Loop through every row in the database
            while (rs.next()) {
                int id = rs.getInt("student_id");
                String firstName = rs.getString("first_name");
                String lastName = rs.getString("last_name");
                int age = rs.getInt("age");
                String email = rs.getString("email");
                
                // 7. Add the row to our visual table
                model.addRow(new Object[]{id, firstName, lastName, age, email});
            }
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
